services:
  - type: web
    name: scheduler-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn django_course_site.django_course_site.wsgi:application
    autoDeploy: true
